name: CI
  
on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update apt cache
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -y libarchive-tools genisoimage
      - name: Build and verify
        run: sudo make check VERBOSE=1
      - name: Create artifact
        run: make artifact VERBOSE=1
      - uses: actions/upload-artifact@v1
        with:
          name: mfslinux-${{ github.sha }}
          path: mfslinux.iso
